#!/Library/Frameworks/EPD64.framework/Versions/Current/bin/python

import time, os
def readFunc():
    """ Lists all functions """
    
    HEADER = \
    " Transit Markov Chain Monte Carlo \n"+\
    " used by the APOSTLE program at the University of Washington, Seattle"
    " Last Updated: "+\
    time.strftime("%Y-%b-%d %H:%M:%S", time.localtime())+"\n"
    
    OutReadMe = open('README','w')
    OutString = ''
    
    for file in os.listdir('.'):
        if file.endswith('.py') and not file.startswith('__init__'):
            OutString += "\n+ "+file+"\n"
            fileObj = open(file,'r')
            for line in fileObj.readlines():
                if line.startswith('def'):
                    OutString += "    "+line[3:]
    
    print >> OutReadMe, HEADER
    print >> OutReadMe, OutString
    OutReadMe.close()

if __name__ == '__main__':

    readFunc()
